name: store
description: top store flutter app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  # state management
  flutter_bloc: ^8.1.1
  # http client
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  # dependency injection
  get_it: ^7.2.0
  # caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # third part
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  flutter_phoenix: ^1.1.0
  connectivity_plus: ^3.0.2
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # third part
  flutter_launcher_icons: ^0.11.0

# set app icon using flutter_launcher_icons plugin
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/i18n/

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/font/Roboto-Light.ttf
#          weight: 300
#        - asset: assets/font/Roboto-Regular.ttf
#          weight: 400
#        - asset: assets/font/Roboto-Medium.ttf
#          weight: 500
#        - asset: assets/font/Roboto-Bold.ttf
#          weight: 700